######################################################################
# Automatically generated by qmake (2.01a) Do. Aug 19 08:49:16 2010
######################################################################

TEMPLATE = lib
TARGET = oh_maphandling
DEPENDPATH += .

INCLUDEPATH += . ../common ../networktools

LIBS += -L../common -loh_common \
 -L../networktools -loh_networktools

# Input
HEADERS += maphandler.h
SOURCES += maphandler.cpp

QT += network